### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by ashleney** [derailedapp/aurora#1]
what the heck is a guild

**Comment by VincentRPS** [comment]
A Guild is a community in Derailed, guilds have channels, roles, audit logs, etc. and with Aurora can be interacted with in a decentralized system by users in other physical servers.

**Comment by elenakrittik** [comment]
a guild is a place where you get derailed

**Comment by EmmmaTech** [comment]
> a guild is a place where you get derailed

that sounds so epic
