### ISSUE TITLE
Move reference Gateway to Elixir

### ISSUE THREAD

**Issue by VincentRPS** [derailedapp/aurora#2]

**Comment by elenakrittik** [comment]
i thought you said gleam doesn't play well with websockets

**Comment by VincentRPS** [comment]
> i thought you said gleam doesn't play well with websockets

It isn't quite about that, it's just that we'd need to do a few workarounds to get cowboy WebSockets working (since cowboy uses Erlang behaviors which you need to do some workarounds to implement in a Gleam app)

**Comment by VincentRPS** [comment]
Update: after working in Gleam for a bit, I've come to the decision that we'll be targeting Elixir instead (again.)
